# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: WebRTCme.Api

on: [workflow_dispatch]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build -c Release WebRTCme.Api/WebRTCme.Api.csproj
    - name: Pack NuGet package
      run: dotnet pack -c Release WebRTCme.Api/WebRTCme.Api.csproj  
    - name: Add source
      run: dotnet nuget add source --username melihercan --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/melihercan/index.json"
    - name: Publish NuGet package to GitHub packages
      run: dotnet nuget push "WebRTCme.Api/bin/Release/WebRTCme.Api.1.0.1.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      
